#read the config file and generate some config

DEFAULT_COVERS = 'PATH TO THE DEFAULT COVER IMAGES PATH'
COVER_IMAGES = 'PATH TO COVER IMAGES'
MEDIA_FILES = 'PATH TO MEDIA FILES FOLDER DEFINES BY THE USER'